ppo:
  steps: 250e3
  seq_rosteps: 32
  num_envs: 128
  gamma: 0.99
  num_self_play: 0
  cliprange: 0.3
task:
  objective: "ALLIED_WEALTH"
eval:
  eval_envs: 0
optimizer:
  lr: "step: 7e-4@0 cos 5e-5@250e3"
  momentum: 0.985
  batch_size: 256
  micro_batch_size: 256
  weight_decay: 0.0001
adr: {}
obs:
  allies: 1
  obs_minerals: 10
  obs_enemies: 0
  obs_map_tiles: 0
  use_privileged: false
policy:
  agents: 1
  nally: 1
  nmineral: 10
  nenemy: 0
  ntile: 0